### ISSUE TITLE
ioBroker add instance failed

### ISSUE THREAD

**Issue by hannesrh** [Newan/ioBroker.easee#13]
**Describe the bug**  
ioBroker add instance failed

**To Reproduce**  
errorlog:
$ ./iobroker add easee  --host raspberrypi4
NPM version: 6.14.10
npm install iobroker.easee@0.1.2 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.easee@0.1.2.
npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2021-05-18T15_14_07_957Z-debug.log
ERROR: host.raspberrypi4 Cannot install iobroker.easee@0.1.2: 1
ERROR: process exited with code 25

**Expected behavior**  
a new instance

**Screenshots & Logfiles**  

&nbsp; | iobroker host.raspberrypi4 Cannot install iobroker.easee@0.1.2: 1
-- | --

**Versions:**  
 - Adapter version: 0.1.2
 - JS-Controller version: 3.2.16
 - Node version: v12.20.1
 - Operating system: Linux raspberrypi4 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux

**Additional context**

**Comment by Newan** [comment]
Please use latest from this repo. The stable Version is waiting for update

**Comment by Newan** [comment]
New Version in stable
