### ISSUE TITLE
update 1.0.1 to 1.0.2 fails

### ISSUE THREAD

**Issue by gidhap** [Newan/ioBroker.easee#15]
Tried to update 1.0.1 to 1.0.2 but failed: Although it says "Adapter "easee" updated, it isn't.

`$ ./iobroker upgrade easee
Update easee from @1.0.1 to @1.0.2
NPM version: 6.14.10
npm install iobroker.easee@1.0.2 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.easee@1.0.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2021-05-26T10_39_54_690Z-debug.log
upload [4] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/words.js words.js application/javascript
upload [3] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/style.css style.css text/css
upload [2] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/index_m.html index_m.html text/html
upload [1] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/easee.png easee.png image/png
upload [0] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/admin.d.ts admin.d.ts video/mp2t
Adapter "easee" updated
process exited with code 0`

Log file:

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'iobroker.easee@1.0.2',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v12.20.1
4 verbose npm-session 363fe634ee576e09
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/iobroker.easee 887ms
8 silly fetchPackageMetaData error for iobroker.easee@1.0.2 No matching version found for iobroker.easee@1.0.2.
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 5838ms
11 verbose type version
12 verbose stack iobroker.easee: No matching version found for iobroker.easee@1.0.2.
12 verbose stack     at pickManifest (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:122:13)
12 verbose stack     at /usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14
12 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
12 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
12 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
12 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
12 verbose stack     at _drainQueueStep (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
12 verbose stack     at _drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
12 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
12 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
12 verbose stack     at processImmediate (internal/timers.js:461:21)
13 verbose cwd /opt/iobroker
14 verbose Linux 4.19.0-6-amd64
15 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.easee@1.0.2" "--loglevel" "error" "--prefix" "/opt/iobroker"
16 verbose node v12.20.1
17 verbose npm  v6.14.10
18 error code ETARGET
19 error notarget No matching version found for iobroker.easee@1.0.2.
20 error notarget In most cases you or one of your dependencies are requesting
20 error notarget a package version that doesn't exist.
21 verbose exit [ 1, true ]
`

**Comment by Newan** [comment]
please try again

**Comment by gidhap** [comment]
Working now, thanks a lot!
