### ISSUE TITLE
log Read-only state "easee.0.XXXX.session.2021.3.currencyId" has been written without ack-flag with value "null"

### ISSUE THREAD

**Issue by torsten3009** [Newan/ioBroker.easee#17]
**Describe the bug**  
Since update to iobroker admin 5.x and Easee Wallbox API 1.0.1 and 1.0.2 I get errors in the log

**To Reproduce**  
1. Go to logs and check warn messsages

removed serial number in log

easee.0 | 2021-06-07 08:19:46.342 | warn | Read-only state "easee.0.EH.session.2020.12.currencyId" has been written without ack-flag with value "null"
-- | -- | -- | --
easee.0 | 2021-06-07 08:19:46.339 | warn | Read-only state "easee.0.EH.session.2021.3.currencyId" has been written without ack-flag with value "null"
easee.0 | 2021-06-07 08:19:46.337 | warn | Read-only state "easee.0.EH.session.2021.4.currencyId" has been written without ack-flag with value "null"
easee.0 | 2021-06-07 08:19:46.335 | warn | Read-only state "easee.0.EH.session.2021.5.currencyId" has been written without ack-flag with value "null"
easee.0 | 2021-06-07 08:19:46.332 | warn | Read-only state "easee.0.EH.session.2021.6.currencyId" has been written without ack-flag with value "null"
easee.0 | 2021-06-07 08:19:46.323 | warn | Read-only state "easee.0.EH.session.2020.12.totalCost" has been written without ack-flag with value "0"
easee.0 | 2021-06-07 08:19:46.314 | warn | Read-only state "easee.0.EH.session.2021.3.totalCost" has been written without ack-flag with value "0"
easee.0 | 2021-06-07 08:19:46.312 | warn | Read-only state "easee.0..session.2021.4.totalCost" has been written without ack-flag with value "0"
easee.0 | 2021-06-07 08:19:46.308 | warn | Read-only state "easee.0..session.2021.5.totalCost" has been written without ack-flag with value "0"
easee.0 | 2021-06-07 08:19:46.307 | warn | Read-only state "easee.0..session.2021.6.totalCost" has been written without ack-flag with value "0"
easee.0 | 2021-06-07 08:19:46.281 | warn | Read-only state "easee.0..session.2020.12.totalEnergyUsage" has been written without ack-flag with value "0"
easee.0 | 2021-06-07 08:19:46.280 | warn | Read-only state "easee.0..session.2021.3.totalEnergyUsage" has been written without ack-flag with value "73.512831"
easee.0 | 2021-06-07 08:19:46.278 | warn | Read-only state "easee.0..session.2021.4.totalEnergyUsage" has been written without ack-flag with value "107.518642"
easee.0 | 2021-06-07 08:19:46.276 | warn | Read-only state "easee.0..session.2021.5.totalEnergyUsage" has been written without ack-flag with value "24.903054"
easee.0 | 2021-06-07 08:19:46.271 | warn | Read-only state "easee.0..session.2021.6.totalEnergyUsage" has been written without ack-flag with value "8.787503"
easee.0 | 2021-06-07 08:19:46.265 | warn | Read-only state "easee.0.EH7.session.2020.total_year" has been written without ack-flag with value "0"

Any idea?

**Comment by Newan** [comment]
Fixed next free time

**Comment by Newan** [comment]
fixed in 1.0.3
