### ISSUE TITLE
chargerOpMode = 6 ?   und Staus möglich ?  (Warten auf Fahrzeug)

### ISSUE THREAD

**Issue by Scotty-89** [Newan/ioBroker.easee#18]
Hallo zusammen,
erstmal vielen Dank für den Adapter leider habe ich damit auch ein paar Problem ...... bzw ggf bin ich auch nur doof ihn zu bedienen ;) 

ich bin gerade etwas am rumspielen mit unseren neuen E-Auto und ioBroker bzw dem Adapter...
eigentlich noch ganz am anfangen über ein blockly frage ich gerade mein Haus Überschuss ab und wenn der einen wert Übersteigt wollte ich eigentlich das Laden beginnen. Nur ich bekomme das schon nicht so recht hin..
Ich setze also den parameter dynamicChargerCurrent = 6 und dann start = true dann passiert ewig nichts ...  in der App steht dann meist "warte auf Fahrzeug" daher meine erste Frage können wir diesen zusätzlichen Status in den adapter bekommen ? 

Aktuell bin ich so nicht in der Lage zu sehen wo das ganze system gerade ist oder was es macht da der chargerOpMode= 2 ist. nach etwas Zeit steht dann in der app "bereit zum Aufladen" chargerOpMode geht dann auf = 6.
kennt das jemand ? 
meine Vermutung nach ein paar test ist das ich wohl im Fahrzeug ab und an das mal genehmigen muss ... wieso auch immer eigentlich ist im auto das also sofort laden hinterlegt ...

zusätzlich ist mir aufgefallen das ich den Vorgang auch nicht mit resume beginnen kann somit kann ich anhand der aktuell verfügbaren States nicht unterscheiben ob ich nun starten muss oder resume reichen würde ...

**Comment by Newan** [comment]
Schau mal bitte im Forum. Gerade Überschussladen wurde da ausführlich behandelt.

**Comment by Scotty-89** [comment]
Hey das mach ich gleich aber dennoch die Frage was ist chargerOpMode = 6 und ist es möglich die "zusätzlichen" status wie pause etc die ja die app anzeigen mit aufzunehmen ?
