### ISSUE TITLE
Feature-request -> max. Ladestrom einstellbar integrieren

### ISSUE THREAD

**Issue by Uwe1984** [Newan/ioBroker.easee#2]
In der Easee-App kann man den maximalen Ladestrom einstellen ( von 6A - 16A ). 
Ggf. ist dieser Datenpunkt auch in der API vorhanden. 
Ich wünsche mir eine Integration von diesem setting.

**Comment by Newan** [comment]
Bitte Objekte einmal löschen zur Sicherheit und Version 1.1.3 verwenden. Configwert heißt dynamicChargerCurrent

**Comment by Uwe1984** [comment]
Ich habe auf Version 1.1.3 ein update gemacht und den Datenpunkt getestet. Tut was er soll. 
Danke
