### ISSUE TITLE
ustable plug in

### ISSUE THREAD

**Issue by ZoltanBrindza** [Newan/ioBroker.easee#20]
Hello
Everything works but quite often the plugin looks out,light up a yellow circle,but after restarting the adapter starts up and is green,someone with a similar problem or solution?
Thanks

**Comment by Newan** [comment]
Please post a debug log if the Adapter stop working

**Comment by ZoltanBrindza** [comment]
![Skjermbilde (5)_LI](https://user-images.githubusercontent.com/74625069/127910342-0a45f286-3ef2-4e82-b22d-e06bc5f1562e.jpg)

**Comment by Newan** [comment]
Ok is ab bug. Debug was helpful. Please set Adapter to debug and send the log as text

**Comment by ZoltanBrindza** [comment]
![Skjermbilde (6)_LI](https://user-images.githubusercontent.com/74625069/127959788-61e73d96-8771-4c8b-8837-ed9f79c1b97c.jpg)
This log thought?

**Comment by Newan** [comment]
Yes! This log as text here if the Adapter stop working. Them i fix it

**Comment by Scotty-89** [comment]
Hey
I can see the same behavior ;) if needed I can also deliver an log the next days.

**Comment by Newan** [comment]
sure the same behavior ;) but i need the complete debug log

**Comment by Newan** [comment]
Ist this Version 1.0.3 ?

**Comment by Scotty-89** [comment]
I run  1.0.2 …
Is the 1.0.3 as Tag or release available?

**Comment by Newan** [comment]
release is in iobroker  latest or over npm available

**Comment by ZoltanBrindza** [comment]
Hi
Thanks
I installed 1.0.3 and see what will be stable
