### ISSUE TITLE
Fehlermeldungen nach Updates

### ISSUE THREAD

**Issue by Scotty-89** [Newan/ioBroker.easee#21]
nachdem ich dem Admin adapter und weitere jetzt aktualisiert habe erhalte ich Fehlermeldungen..
Der Adapter läuft bei mir im 5 Sekunden Zyklus da es mit dem SignalR in Verbindung mit meiner PV Überschuss Regelung nicht richtig klappt bzw. dort das System schwingt .. 

<html>
<body>

easee.0 | 2021-08-09 16:54:02.863 | debug | Chargers ausgelesen
-- | -- | -- | --
easee.0 | 2021-08-09 16:54:02.708 | debug | read new states from the API
easee.0 | 2021-08-09 16:53:57.858 | error | Error: Easee API error on charger state - stop refresh
easee.0 | 2021-08-09 16:53:57.858 | error | Error: Request failed with status code 429
easee.0 | 2021-08-09 16:53:57.697 | debug | {"id":"EHTZSSUL","name":"EHTZSSUL","color":4,"createdOn":"2021-03-26T09:20:00.864375","updatedOn":"2021-06-21T17:43:31.270762","backPlate":null,"levelOfAccess":null,"productCode":null}
easee.0 | 2021-08-09 16:53:57.696 | debug | Charger gefunden
easee.0 | 2021-08-09 16:53:57.696 | debug | [{"id":"EHTZSSUL","name":"EHTZSSUL","color":4,"createdOn":"2021-03-26T09:20:00.864375","updatedOn":"2021-06-21T17:43:31.270762","backPlate":null,"levelOfAccess":null,"productCode":null}]
easee.0 | 2021-08-09 16:53:57.696 | debug | Chargers ausgelesen
easee.0 | 2021-08-09 16:53:57.541 | debug | read new states from the API
easee.0 | 2021-08-09 16:53:52.676 | error | Error: Easee API error on charger state - stop refresh
easee.0 | 2021-08-09 16:53:52.676 | error | Error: Request failed with status code 429
easee.0 | 2021-08-09 16:53:52.528 | debug | {"id":"EHTZSSUL","name":"EHTZSSUL","color":4,"createdOn":"2021-03-26T09:20:00.864375","updatedOn":"2021-06-21T17:43:31.270762","backPlate":null,"levelOfAccess":null,"productCode":null}
easee.0 | 2021-08-09 16:53:52.528 | debug | Charger gefunden

</body>
</html>

**Comment by Newan** [comment]
429 = Too Many Requests

Bitte mal alle Apps aus und ggf mal 24h warten. Hier läufts mit neuster Version

**Comment by Scotty-89** [comment]
Hey,

ich hatte den adapter nun  über Nacht aus.. 
leider keine Besserung das Problem kommt immer wieder..
vor den Update hatte es mit einem 5sekunden Intervall funktioniert ... seltsam.
Gibt es den von der APi eine DOku bezüglich der maximalen möglichen req pro Stunde ?

**Comment by Newan** [comment]
Musst du bei easee nachfragen, ggf bist du gesperrt: https://api.easee.cloud/index.html
