### ISSUE TITLE
Feature Request:  Smart Charging and Schedules controls

### ISSUE THREAD

**Issue by EdExley** [Newan/ioBroker.easee#27]
Per API Documentation there are controls to enable smart charging and override schedules available. Could these be integrated, since I would like to have smart charging when no PV energy is available, but of course start charging immediately when PV power is available.

Thanks!

**Comment by EdExley** [comment]
Thanks for adding the data point smart charging to the adapter in the 1.0.5 release. Currently it is set as read only. Could this be changed to be writable as well, so that smart charging can be enabled or disabled via iobroker scripts? Technically this should be possible, see https://developer.easee.cloud/docs/controlling-a-charger.

Thank you very much!

**Comment by Newan** [comment]
please explain me what smart charging do?

**Comment by marwin79** [comment]
I was working on the same change. The strange thing is, that if I press the smart button on the charger, the status is changing between white and blue LED, but nothing else happens.

```
2021-11-05 20:42:19.036  - info: easee.0 (2487254) New value over SignalR for: EH809509.config.smartCharging, value: 0
2021-11-05 20:42:19.037  - info: easee.0 (2487254) New value over SignalR for: EH809509.status.ledMode, value: 24
2021-11-05 20:43:11.693  - info: easee.0 (2487254) New value over SignalR for: EH809509.config.smartCharging, value: 1
2021-11-05 20:43:11.694  - info: easee.0 (2487254) New value over SignalR for: EH809509.status.ledMode, value: 21
```

As soon as I change .config.smartCharging to true in ioBroker, the LED turns blue and the charger starts charging immediatly.
I think that's kind of the idea of "Smart Charging"? The problem with this is, that with changing to that mode, the weekly schedule is disabled (if I check it in the app), and it is not re-enabled if I change back smartCharging to false... I have to re-enable the schedule via app.

**Comment by EdExley** [comment]
Smart charging is a feature that works with an hourly energy rate like tibber. Tibber can control the charger to only charge when prices are low. So I can set up a schedule in the Tibber app when I would like the charging to be done and for how long I would like to charge each day. Tibber will then start charging when prices will be low for the duration of the charge. 

My ideal scenario would be to have a switch in iobroker to switch between PV surplus charging (1 P, smart charging off, starts when I plug in) and “bad weather charging” (3P, smart charging on, uses lowest prices from Tibber). For that I would need to be able to switch smart charging on and off from iobroker. 

I hope this clears things up a bit.

**Comment by Newan** [comment]
Thanks, pls Check the last release
