### ISSUE TITLE
Feature-request --> Einstellung der Phasen 1/3 

### ISSUE THREAD

**Issue by Uwe1984** [Newan/ioBroker.easee#3]
Die Easee App beinhaltet auch die ein Umschaltung zwischen den Phasen 1 und 3. 
Eventuell bietet diesen Schalter ach die API von Easee. 
Eine Integration in Iobroker wäre super.

**Comment by Newan** [comment]
Sollte in der Version 0.1.x schon gehen. Bitte einfach mal testen: .config.phaseMode

**Comment by Uwe1984** [comment]
Funktioniert wunder bar. Danke
