### ISSUE TITLE
Password logged plaintext

### ISSUE THREAD

**Issue by marwin79** [Newan/ioBroker.easee#31]
https://github.com/Newan/ioBroker.easee/blob/410c00426254c578a103f858e1952f379256e037/main.js#L112

https://developer.easee.cloud/docs/get-started#responsibilities

Only for "debug", but I think this should be removed completely.

**Comment by Newan** [comment]
Why? Debug is not the normal state. User where check the password have now a chance to check it?

**Comment by marwin79** [comment]
I just don't see the reason for having the password in the logfile... Either it's accepted or not, but it does not really help if it is logged...
But maybe there are other opinions.

**Comment by Newan** [comment]
Grundsätzlich stimmt das, wir speichern es aber verschlüsselt und da gab es mal Probleme. Da die nun weg sind nehme ich es raus in next release
