### ISSUE TITLE
Question: List of Led-States

### ISSUE THREAD

**Issue by roman1528** [Newan/ioBroker.easee#37]
Hi.
Is there any list of led states. I do not have any car yet to test the led states myself.
A list with assignments with led state number and how the led-strip of the box is light up would be nice.

Thanks for that.

**Comment by marwin79** [comment]
https://support.easee.com/help/s/article/What-does-the-different-colors-on-the-light-strip-mean

Or in the manual, on page 19:
https://easee-media-content-ec8c9e4.s3.eu-west-1.amazonaws.com/wp-content/uploads/2021/02/28131000/EN_Easee_HomeCharge_Guide.pdf

**Comment by roman1528** [comment]
Yeah nice... But which state is the corresponding state number in iobroker.easee? Maybe my question wasn't detailed enough...

**Comment by maegnes** [comment]
@roman1528 not sure if it's quite up to date. But here's a list of all states:

https://developer.easee.cloud/docs/enumerations
