### ISSUE TITLE
state.dynamic - Einträge fehlen

### ISSUE THREAD

**Issue by TMHEINE** [Newan/ioBroker.easee#42]
Hallo, 
Ich habe den Adapter neu installiert in der Version 1.0.5

Verbindung und alles klappt soweit. Jedoch bekomme ich bei jedem Neustart des Adapters folgende Warnungen:

easee.0 (4744) State "easee.0.XXXXXXXX.status.dynamicCircuitCurrentP1" 
has no existing object, this might lead to an error in future versions
 easee.0 (4744) State "easee.0.XXXXXXXX.status.dynamicCircuitCurrentP2" 
has no existing object, this might lead to an error in future versions
 easee.0 (4744) State "easee.0.XXXXXXXX.status.dynamicCircuitCurrentP3" 
has no existing object, this might lead to an error in future versions

Auch über Expert-Modus, schaffe ich es nicht, dies Objekte anzulegen. Sollten diese Objekte nicht vom Adapter selbst angelegt werden?

Mach ich da irgendwo einen Fehler?

**Comment by camast** [comment]
Das Gleiche sehe ich auch. Du kannst die Datenpunkte manuell erzeugen, indem Du den angehängten Code unter "iobroker/Objekte/"Objektbaum aus JSON-Datei hinzufügen" (Symbolleiste/2. Symbol von rechts) importierst
Vorher natürlich XXXXXXXX gegen Deine ID tauschen ...

[Datenpunkte-easee.txt.txt](https://github.com/Newan/ioBroker.easee/files/8348547/Datenpunkte-easee.txt.txt)

**Comment by TMHEINE** [comment]
Hat geklappt! Vielen Dank!
