### ISSUE TITLE
Easee Cloud API update with backwards compatibility break

### ISSUE THREAD

**Issue by marwin79** [Newan/ioBroker.easee#45]
Easee Notification:
We will remove one of our login endpoints during this maintenance. If you have any systems relying on https://api.easee.cloud/api/accounts/token please move this to https://api.easee.cloud/api/accounts/login before this maintenance.

The two endpoints should be identical from an external pov. so please swap to the new URL and verify the implementation before 1st of July.

**Comment by marwin79** [comment]
Legacy: https://developer.easee.cloud/reference/post_api-accounts-token
New: https://developer.easee.cloud/reference/post_api-accounts-login

**Comment by Newan** [comment]
thanks
