### ISSUE TITLE
Charging Data cannot be changed

### ISSUE THREAD

**Issue by jhg28** [Newan/ioBroker.easee#48]
Hi,

tried to change the information in dynamicCircuitCurrentPX, which was not successful.

Every change was written to to the value in the datapoint and after some seconds it's automatically changed back to the earlier one.

I'm using Adapter-Version 1.06 with NPM 8.11.0 and NodeJS 16.5.1

**Comment by marwin79** [comment]
Check "Help" Section here https://github.com/Newan/ioBroker.easee

dynamicCircuitCurrentPX -> All phases must be set within 500ms (script) otherwise the phase will be set to 0.
