### ISSUE TITLE
Zeitanzeige Ladezeit? - Überhaupt möglich?

### ISSUE THREAD

**Issue by Michaelnorge** [Newan/ioBroker.easee#5]
Endlich!!! Die Easee-Box ist mit ioBroker steuerbar! Toll gemacht!!!

Dies ist eigentlich kein Issue, mehr eine Logik-Frage:
Ich war Kunde bei Tibber, die meine Wallbox steuerte.
Ich konnte dort angeben, zu welcher Zeit mein Auto (Ioniq) aufgeladen sein soll.
Daher bin ich davon ausgegangen, daß die Easee-Box von meinem Auto darüber bescheid wie lange er für das Aufladen benötigen wird und dachte daher, in den Objekten eine Art "Countdown" zu finden. 
Dies ist nicht der Fall.

Fehlt diese Integration einfach oder habe ich einen Denkfehler?

Grüße für die tolle Arbeit!
Michael

**Comment by warp735** [comment]
Denkfehler...

Tibber holt sich den aktuellen Ladestand des Autos von der Herstellerseitigen App. Nach meinem Kenntnisstand gibts für den Ioniq ja nichts. Drum kennt auch "niemand" den Ladestand ;)

**Comment by Newan** [comment]
Daten von deinem Auto sollte hier besprochen werden: https://github.com/ioBroker/AdapterRequests/issues/403

**Comment by Michaelnorge** [comment]
Danke Euch!
