### ISSUE TITLE
Warnings during Installation

### ISSUE THREAD

**Issue by jhg28** [Newan/ioBroker.easee#50]
Hi,
the problem, that the charging power does not working is still there.
Tried to install the adapter once more.

There are a lot of warnings:

_$ iobroker add easee auto --host iobroker-s --debug

NPM version: 8.11.0

Installing iobroker.easee@1.0.7... (System call)

npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers

npm WARN deprecated har-validator@5.1.5: this library is no longer supported

npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.

npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues._

Some of these created maybe the issue on my system.
Can you please check.

**Comment by Newan** [comment]
bitte commit prüfen, ob der das fixed. danke
