### ISSUE TITLE
Seit einiger Zeit lauter Fehlermeldungen im log. 

### ISSUE THREAD

**Issue by Michaelnorge** [Newan/ioBroker.easee#55]
**Describe the bug**  
Ich bekomme seit geraumer Zeit halbstündlich Fehlermeldungen im log, die so vorher nicht da waren. Es handelt sich um Errorfehler 500, 502 und 504. 
Laut Google sollen es Serverseitige Fehler sein, aber mehr weiß ich leider auch nicht.

Im Debug sind keine Fehler ersichtlich. Login und alles andere ist ok - sind halt nur diese Fehlermeldungen, mit denen ich nichts anfangen kann.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/42386692/197406957-19c4fc3f-8808-492f-aef8-e0fc3b576e5c.png)
![image](https://user-images.githubusercontent.com/42386692/197407066-7eea5873-3998-4690-bdea-625f49524959.png)

**Versions:**  
 - Adapter version: 1.07
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: Raspberry Pi. Linux

**Comment by manny4566** [comment]
Gleiches Problem. Die Charger können nicht mehr ausgelesen werden seit 1-2 Tagen. Hat Easse etwas an der API verändert ?

**Comment by marwin79** [comment]
Ob es generell ein Problem gibt, weiss ich (noch) nicht.

Aber jetzt grad im Moment ist die Cloud leider wiedermal down :(
https://status.easee.com/

Der Druck von über 350 Users scheint Easee noch nicht genug zu sein um endlich eine local API zu bringen.
https://feedback.easee.com/b/ideas/local-simple-api/

**Comment by Newan** [comment]
Cloud ist wieder verfügbar. Nach maximal restart des Adapter sollte es wieder gehen?

**Comment by Michaelnorge** [comment]
Jepp, alles ok!
