### ISSUE TITLE
Adapter restarting due to uncaught exception

### ISSUE THREAD

**Issue by souhl** [Newan/ioBroker.easee#6]
Adapter cannot start cause of an uncaught exception.

host.iobroker | 2021-04-25 19:20:36.740 | warn | Do not restart adapter system.adapter.easee.0 because restart loop detected
-- | -- | -- | --
host.iobroker | 2021-04-25 19:20:36.740 | info | Restart adapter system.adapter.easee.0 because enabled
host.iobroker | 2021-04-25 19:20:36.739 | error | instance system.adapter.easee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
easee.0 | 2021-04-25 19:20:36.144 | warn | (4052739) Terminated (UNCAUGHT_EXCEPTION): Without reason
easee.0 | 2021-04-25 19:20:36.143 | info | (4052739) terminating
easee.0 | 2021-04-25 19:20:36.143 | info | (4052739) Adaptor easee cleaned up everything...
easee.0 | 2021-04-25 19:20:36.133 | error | (4052739) Request failed with status code 400
easee.0 | 2021-04-25 19:20:36.133 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
easee.0 | 2021-04-25 19:20:36.133 | error | at endReadableNT (_stream_readable.js:1241:12)
easee.0 | 2021-04-25 19:20:36.133 | error | at IncomingMessage.emit (events.js:326:22)
easee.0 | 2021-04-25 19:20:36.133 | error | at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
easee.0 | 2021-04-25 19:20:36.133 | error | at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
easee.0 | 2021-04-25 19:20:36.133 | error | at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
easee.0 | 2021-04-25 19:20:36.133 | error | (4052739) Error: Request failed with status code 400
easee.0 | 2021-04-25 19:20:36.132 | error | (4052739) unhandled promise rejection: Request failed with status code 400
easee.0 | 2021-04-25 19:20:36.132 | error | (4052739) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Versions:**  
 - Adapter version: 1.0.1
 - JS-Controller version: 3.2.16
 - Node version: v12.20.0
 - Operating system: ubuntu

**Comment by souhl** [comment]
It was a changed password.. Would be great to add some error handling when password was changed.

**Comment by Newan** [comment]
Please check new Version
