### ISSUE TITLE
Adapter läuft nicht mit Node.js v18.15.0

### ISSUE THREAD

**Issue by TMHEINE** [Newan/ioBroker.easee#60]
Nach dem Update Node.js von V16 auf V18 läuft der Adapter nicht mehr.
Fehler:
- Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
- unhandled promise rejection: self is not defined
- ReferenceError: self is not defined at new FetchHttpClient (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/FetchHttpClient.js:81:42) at new DefaultHttpClient (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/DefaultHttpClient.js:27:32) at new HttpConnection (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/HttpConnection.js:99:49) at HubConnectionBuilder.build (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/HubConnectionBuilder.js:117:26) at Easee.startSignal (/opt/iobroker/node_modules/iobroker.easee/main.js:48:14) at Easee.onReady (/opt/iobroker/node_modules/iobroker.easee/main.js:135:26)
- self is not defined

![grafik](https://user-images.githubusercontent.com/6831714/226175432-ec15fcba-0684-4bf2-b43f-98b7d1c25e46.png)

Was kann ich da tun?

**Comment by lastoks** [comment]
Gleiches Problem bei mir nach dem Update auf Nodejs 18

**Comment by Newan** [comment]
Könnt ihr das mal bitte mit v19 testen. Hab es gerade versucht bei mir nachzustellen, aber habe keinen Fehler?
Ggf nur mit v18 so

**Comment by gidhap** [comment]
@Newan OK. Soweit ich weiss ist die V18.15.0 die aktuell höchste empfohlene Version, habe produktiv keine höhere am Laufen. Ich versuch mal eine Testinstanz mit V19 in der VM zu machen. Kann aber noch ein zwei Tage dauern.

**Comment by gidhap** [comment]
@Newan Ich habe eine neue VM (auch Buster wie meine Prod.) mit neuem IoBroker aufgesetzt und mal nur den Easee Adapter installiert, dann NodeJS auf 18.15.0 gebracht. Der Easee adapter wird geladen und funktioniert. Abgesehen von der Meldung
`easee.0 | 2023-04-06 09:26:30.460 | info | undefined is not a valid state value for id "easee.0.xxxxxx.status.latestFirmware"
easee.0 | 2023-04-06 09:26:01.269 | warn | State "easee.0.xxxxxx.session.2023.total_year" has no existing object, this might lead to an error in future versions`
die ich jetzt erst mal ignoriere. Oder kann das mit den o.a. Fehlern zusammenhängen?
Nun frage ich mich wie ich den Fehler in der Produktiv Instanz finden kann. Habe ja von coding keinen Plan. :(

**Comment by jhg28** [comment]
Habe denselben Fehler mit 18.15.
Leider aktualisiert und den Eintrag hier vorher nicht gesehen.
Meldungen sind dieselben wie oben.

**Comment by Newan** [comment]
bitte commit prüfen, ob der das fixed. danke

**Comment by jhg28** [comment]
Adapter läuft nach Neuinstallation wieder.

Folgender Hinweis kommt immer noch:
State "easee.0.EH3K3T5J.status.smartCharging" has no existing object, this might lead to an error in future versions

**Comment by gidhap** [comment]
Adapter gelöscht und neu installiert, läuft wieder. DANKE !
Hier die noch verbliebenen Meldungen
easee.0 | 2023-04-10 15:20:21.348 | info | undefined is not a valid state value for id "easee.0.xxxxxx.status.latestFirmware"
easee.0 | 2023-04-10 15:19:52.287 | warn | State "easee.0.xxxxxx.session.2023.total_year" has no existing object, this might lead to an error in future versions
easee.0 | 2023-04-10 15:19:52.285 | warn | State "easee.0.xxxxxx.session.2022.total_year" has no existing object, this might lead to an error in future versions
easee.0 | 2023-04-10 15:19:52.257 | warn | State "easee.0.xxxxxx.session.2021.total_year" has no existing object, this might lead to an error in future versions
`

**Comment by modmax** [comment]
Nach Neuinstallation von GitHub ist das Problem gelöst. Dankeschön!

**Comment by TMHEINE** [comment]
Auch bei mir ist das Problem durch eine Neuinstallation aus dem Git gelöst.
Den fehlenden Datenpunkt für "easee.0.xxxxxxx.status.smartCharging" hatte ich ja schon ne weile immer manuell angelegt.
Danke
