### ISSUE TITLE
12 Battery drained to 5V, despite setting to prevent it

### ISSUE THREAD

**Issue by gidhap** [Newan/ioBroker.easee#61]
By accident, in the instance settings,  I entered 100 Requests per day. I did want 3 only, so my fault.
However, the setting to protect the battery did not work. Today the battery was drained to 5 volts, so I had to manually open the vehicle and recharge the battery. Hope it isn't dead.
![image](https://user-images.githubusercontent.com/28500973/234546035-4373086a-3633-4a90-b933-dda99388814b.png)
Adapter Version 2.3.2

**Comment by Newan** [comment]
pls bluelink adapter. here is easee!!

**Comment by gidhap** [comment]
dang, - sorry
