### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by TMHEINE** [Newan/ioBroker.easee#62]
Hi,

aktuell habe ich das Problem, daß ich keine gültige verbindung zum Server bekommen (siehe Log)

Ist das nur bei mir, oder haben das andere auch?

<html><body>

easee.0 | 2023-05-10 12:11:13.973 | error | Failed  to complete negotiation with the server: Error: The "/hubs" endpoint is  moved from api.easee.cloud to streams.easee.com: Status code '410'
-- | -- | -- | --
easee.0 | 2023-05-10 12:11:13.972 | error | Error:  Failed to complete negotiation with the server: Error: The "/hubs"  endpoint is moved from api.easee.cloud to streams.easee.com: Status code  '410'    at HttpConnection._getNegotiationResponse  (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/HttpConnection.js:256:35)     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)    at async  HttpConnection._startInternal  (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/HttpConnection.js:172:41)     at async HttpConnection.start  (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/HttpConnection.js:75:9)     at async HubConnection._startInternal  (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/HubConnection.js:132:9)     at async HubConnection._startWithStateTransitions  (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/HubConnection.js:109:13)
easee.0 | 2023-05-10 12:11:13.971 | error | unhandled  promise rejection: Failed to complete negotiation with the server:  Error: The "/hubs" endpoint is moved from api.easee.cloud to  streams.easee.com: Status code '410'
easee.0 | 2023-05-10 12:11:13.969 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

</body>
</html>

**Comment by Newan** [comment]
Letzten commit von heute testen
