### ISSUE TITLE
Kannst Du noch den Enabled=on/off einbauen?

### ISSUE THREAD

**Issue by Blackbat72** [Newan/ioBroker.easee#63]
in der config gibt es den Datenpunkt isEnabled = true/false.
Dieser lässt sich aber nicht schreiben.
ich hab reausgefunden, dass es aber in der API über
https://api.easee.cloud/api/chargers/ID/settings 
den Schalter enabled = true/false gibt, welcher auch funktioniert.

Könntest Du den noch bei den Commands mit einbauen.
Das wäre echt toll, denn ich will die Box immer automatisch ausschalten, wenn das Kabel gezogen wird, und einschalten, entweder wenn ich nach Hause komme und der Accu eine bestimmten Wert unterschritten hat, bzw. auch auf Knopfdruck in meiner VIS

Danke Dir

**Comment by kofi1990** [comment]
+1. wär super - gleiches szenario wie blackbat

**Comment by Newan** [comment]
Bitte testen
