### ISSUE TITLE
undefined is not a valid state value for id "easee.0.xxxx.status.latestFirmware"

### ISSUE THREAD

**Issue by fazode** [Newan/ioBroker.easee#64]
Trotz dem Vorgehen aus dem Fehler #58 und zwar dem löschen der Abfrage in der enum.js erhalte ich noch immer in den Protokollen diesen Fehler. Auch der restart des iobroker hat nicht geholfen.

easee.0 | 2023-05-24 19:53:03.161 | info | undefined is not a valid state value for id "easee.0.xxxxxxxx.status.latestFirmware"

So sieht meine enum.js nun aus:
 //Status
    46: '.status.ledMode',
    68: '.status.wiFiAPEnabled',
    82: '.status.chargerFirmware',
    96: '.status.reasonForNoCurrent',
    102: '.status.smartCharging',
    103: '.status.cableLocked',
    109: '.status.chargerOpMode',
    110: '.status.outputCurrent',
    120: '.status.totalPower',
    122: '.status.energyPerHour',
    124: '.status.lifetimeEnergy',
    132: '.status.wiFiRSSI',
    150: '.status.TempMax',
    //xx: ".status.voltage",
    //xx: ".status.isOnline"
    182: '.status.inCurrentT2',
    183: '.status.inCurrentT3',
    184: '.status.inCurrentT4',
    185: '.status.inCurrentT5',
    190: '.status.inVoltageT1T2',
    191: '.status.inVoltageT1T3',
    192: '.status.inVoltageT1T4',
    193: '.status.inVoltageT1T5',
    194: '.status.inVoltageT2T3',
    195: '.status.inVoltageT2T4',
    196: '.status.inVoltageT2T5',
    197: '.status.inVoltageT3T4',
    198: '.status.inVoltageT3T5',
    199: '.status.inVoltageT4T5',

**Comment by Bulls91** [comment]
ich habe exakt den gleichen Fehler. Gibt es Abhilfe?

**Comment by Bulls91** [comment]
konnte das Problem wohl nun lösen in dem ich im IOBroker unter Adapter die Experteneinstellung aktiviert habe und diesen easee Wallbox-Adapter nochmals über den GitHub Link hier installiert/geupdatet habe

**Comment by fazode** [comment]
Auch wenn ich es mir nicht erklären kann aber Bulls91 hat recht! Ich bin genau so vorgegangen und das Problem ist weg.
TOP Danke Bulls91

**Comment by Newan** [comment]
Fehlt Zeit und damit eine neue stable Version.
Sorry

**Comment by fazode** [comment]
Ich werde mich nicht beschweren, bin froh dass es den Adapter gibt. 
Dafür auf jeden Fall einen herzlichen Dank!

**Comment by Newan** [comment]
Version im unstable, wenn das geht mach ich eine neue stable
