### ISSUE TITLE
Error: Forbidden at new HttpError

### ISSUE THREAD

**Issue by torsten3009** [Newan/ioBroker.easee#65]
**Describe the bug**  

**To Reproduce**  
1. Go to '"start instanz
2. Click on iobroker logs

`

2023-06-02 14:35:47.031 | error | Forbidden

easee.0 | 2023-06-02 14:35:47.030 | error | Error: Forbidden at new HttpError (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/Errors.js:27:24) at FetchHttpClient.<anonymous> (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/FetchHttpClient.js:154:35) at step (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/FetchHttpClient.js:52:23) at Object.next (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/FetchHttpClient.js:33:53) at fulfilled (/opt/iobroker/node_modules/@microsoft/signalr/dist/cjs/FetchHttpClient.js:24:58) at processTicksAndRejections (node:internal/process/task_queues:96:5)
easee.0 | 2023-06-02 14:35:47.029 | error | unhandled promise rejection: Forbidden
easee.0 | 2023-06-02 14:35:47.027 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

`

**Expected behavior**  
no errors in past

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.0.7
 - JS-Controller version: 4.0.24
 - Node version: v16.20.0
 - Operating system:  debian

**Additional context**

**Comment by Newan** [comment]
Glaube du musst auf node 18
