### ISSUE TITLE
Update from 1.0.7 to 1.0.8 fails

### ISSUE THREAD

**Issue by schweiger2** [Newan/ioBroker.easee#66]
**Describe the bug**  
Easee-Adapter in iobroker shows update from 1.0.7 to 1.0.8 in info-tab. Update remains on 1.0.7. 
Deinstallation of adapter done. New install logs 1.0.8 but shows up with 1.0.7 again, also shows update in info-tab again.
Log shows only a few lines (see below), also after new install.

**Screenshots & Logfiles**  

`
iobroker@iobroker:~$ iob upgrade easee --debug

  | Would you like to upgrade easee from @1.0.7 to @1.0.8 now? [(y)es, (n)o]: y
  | Update easee from @1.0.7 to @1.0.8
  | NPM version: 9.5.1
  | Installing iobroker.easee@1.0.8... (System call)
  |  
  | up to date in 2s
  |  
  | 50 packages are looking for funding
  | run `npm fund` for details
  | upload [4] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/admin.d.ts admin.d.ts video/mp2t
  | upload [3] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/easee.png easee.png image/png
  | upload [2] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/index_m.html index_m.html text/html
  | upload [1] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/style.css style.css text/css
  | upload [0] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/words.js words.js application/javascript
`

**Versions:**  
 - Adapter version: 1.0.7 / 1.0.8
 - JS-Controller version: 4.0.24
 - Node version: 18.16.1
 - Operating system: Debian 12 Bookworm

**Comment by Voodoo2man** [comment]
Same here

**Comment by Newan** [comment]
Sorry i check this soon

**Comment by Newan** [comment]
bitte nochmal testen ob die Änderung ausreicht oder ich eine 1.0.9 nach npm hochladen muss

**Comment by spoeh-man** [comment]
Schein eine 1.0.9 zu brauchen

$ ./iobroker upgrade easee
Update easee from @1.0.7 to @1.0.8
NPM version: 9.5.1
Installing iobroker.easee@1.0.8... (System call)
up to date in 10s
142 packages are looking for funding  run `npm fund` for details
upload [4] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/admin.d.ts admin.d.ts video/mp2t
upload [3] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/easee.png easee.png image/png
upload [2] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/index_m.html index_m.html text/html
upload [1] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/style.css style.css text/css
upload [0] easee.admin /opt/iobroker/node_modules/iobroker.easee/admin/words.js words.js application/javascript
process exited with code 0

**Comment by Voodoo2man** [comment]
Über Github konnte ich 1.0.8 jetzt installieren.
Über die normale iobroker Update Funktion hatte es weiterhin nicht funktioniert.

**Comment by schweiger2** [comment]
Auch bei mir hat es über github funktioniert, über den info-tab jedoch nicht.Log zeigt noch Folgendes:easee.02023-07-09 20:30:19.636warnState "easee.0.EH7VT2AX.status.smartCharging" has no existing object, this might lead to an error in future versionseasee.02023-07-09 20:30:19.630warnState "easee.0.EHTQ2XWK.status.smartCharging" has no existing object, this might lead to an error in future versionsAm 09.07.2023 um 20:27 schrieb Voodoo2man ***@***.***>:﻿
Über Github konnte ich 1.0.8 jetzt installieren.
Über die normale iobroker Update Funktion hatte es weiterhin nicht funktioniert.

**Comment by Hildesen** [comment]
Bei mir auch, über npm ging es, anders nicht...

**Comment by Newan** [comment]
1.0.9 released
