### ISSUE TITLE
Dynamic Charging

### ISSUE THREAD

**Issue by souhl** [Newan/ioBroker.easee#8]
Hi Newan,

I am currently working on a ioBroker Script to get the Easee intergrated into openWB by using MQTT and ioBroker as "gateway". Goal is to get Smart Charging working with openWB and Easee.

So far it looks good. But I am struggling with the dynamic charging.
I am trying to use "dynamicChargerCurrent", but this seems to be not working.
I saw your comment in one of ioBroker Forums on the issue Easee had with this a month back.

Is this the reason why I cannot use it?

Thanks in advance
Sascha

**Comment by Newan** [comment]
Please report once in the forum, believe this is not an adapter error. The dynamics is on easee side what erroneous and not all settings work

**Comment by Newan** [comment]
clear in forum
